# **Exercise**
ref: [EDA 15Questions - Using Pandas !!](https://www.kaggle.com/boydbigdatarpg/)

## Titanic Dataset

**Survival:**	Survival	0 = No, 1 = Yes

**Pclass:**	Ticket class	1 = 1st, 2 = 2nd, 3 = 3rd

**Sex:**	Sex

**Age:**	Age in years

**SibSp:**	number of siblings / spouses aboard the Titanic

**Parch:**	number of parents / children aboard the Titanic

**Ticket:**	Ticket number

**Fare:**	Passenger fare

**Cabin:**	Cabin number

**Embarked:**	Port of Embarkation	C = Cherbourg, Q = Queenstown, S = Southampton

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/titanic.csv')

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

**How many passenger in Pclass 1?**

In [4]:
# YOUR C
df[df['Pclass'] == 1]['PassengerId'].count()

np.int64(216)

**How many female dead in dataset and calculated in percentages?**

In [5]:
# YOUR CODE HERE
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

**Which is the most age of dead passenger? (frequency)**

In [6]:
# YOUR CODE HERE

**Average age of dead female passengers and dead male passengers**

In [7]:
# YOUR CODE HERE
female = df[df['Sex'] == 'female']['Age'].mean()
male = df[df['Sex'] == 'male']['Age'].mean()
print(f'female = {female}')
print(f"male = {male}")

female = 27.915708812260537
male = 30.72664459161148

**Which columns has null value ? If it has null value how many null rows in each columns**

In [8]:
# YOUR CODE HERE
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

**In Age column replace null value with average value and then check null again**

In [9]:
# YOUR CODE HERE
df['Age'] = df['Age'].fillna(df['Age'].mean())
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

**Average Ticket price of each Pclass ?**

In [10]:
# YOUR CODE HERE

**Average Ticket price of each Pclass that passenger died ?**

In [11]:
# YOUR CODE HERE

**Average Ticket price of each Pclass that passenger survived ?**

In [12]:
# YOUR CODE HERE

**Average Ticket price of each Pclass, calculated by all pasengers, dead passengers, and survived passengers ?**

In [13]:
# YOUR CODE HERE

**Which port has the best rate survived?**

C = Cherbourg, Q = Queenstown, S = Southampton

In [14]:
# YOUR CODE HERE

**Find the youngest and oldest people on Titanic**

**[Hint]** you can use **.idxmin()** to find index of lowest value and  **.idxmax()** to find index of highest value.

In [15]:
# YOUR CODE HERE

In [16]:
# YOUR CODE HERE

**List of the first 3 who paid the most for the ticket and the top 3 who paid the cheapest**

In [17]:
# YOUR CODE HERE

In [18]:
# YOUR CODE HERE