# Pandas (2)

Let's learn more advanced features of Pandas

**Outline**
- Function application
- Grouping and Aggregating
- Joining Dataframes
- Working with Text Data

In [2]:
import numpy as np
import pandas as pd

## Function application

To apply your own or another library’s functions to pandas objects, you should be aware of the three methods below.

###1. Row or column-wise function application
Arbitrary functions can be applied along the axes of a DataFrame using the `apply()` method, which, like the descriptive statistics methods, takes an optional `axis` argument:

In [3]:
np.random.randn(8, 3)

array([[ 0.50038826, -0.92762113, -0.59475351],
       [ 1.14054633,  0.83045734,  0.44456303],
       [-0.57074311, -1.36717378, -0.68138894],
       [ 0.84340909,  1.29454675, -0.50431835],
       [ 0.79358106, -0.52095629, -0.42572579],
       [-0.64831513,  1.22158439, -1.41095814],
       [ 0.13451283,  0.75970478, -0.48397648],
       [ 0.14636897, -1.15366742, -0.27720283]])

In [4]:
index = pd.date_range("1/1/2000", periods=8)
df = pd.DataFrame(np.random.randint(0, 100, size=(8,4)), index=index, columns=["A", "B", "C", "D"])

In [ ]:
df

             A   B   C   D
2000-01-01  69  24  64  77
2000-01-02  21  47  80  78
2000-01-03  39  34  26   0
2000-01-04  21   7  52  75
2000-01-05  44  58  53  33
2000-01-06  65   9  99  88
2000-01-07   1   9  11  76
2000-01-08   4  12  75  83

In [ ]:
df.apply(np.mean) #default axis = 0 or ‘index’: apply function to each column.

A    33.00
B    25.00
C    57.50
D    63.75
dtype: float64

In [ ]:
df.apply(np.mean, axis=1) # axis = 1 or ‘columns’: apply function to each row.

2000-01-01    58.50
2000-01-02    56.50
2000-01-03    24.75
2000-01-04    38.75
2000-01-05    47.00
2000-01-06    65.25
2000-01-07    24.25
2000-01-08    43.50
Freq: D, dtype: float64

In [ ]:
# df.apply(lambda x: x.max() - x.min(), axis=1)
def calRange(x):
  return x.max() - x.min()

df.apply(calRange, axis=1)

2000-01-01    53
2000-01-02    59
2000-01-03    39
2000-01-04    68
2000-01-05    25
2000-01-06    90
2000-01-07    75
2000-01-08    79
Freq: D, dtype: int64

You may also pass additional arguments and keyword arguments to the apply() method. For instance, consider the following function you would like to apply:

In [ ]:
def subtract_and_divide(x, sub, divide=1):
  return (x - sub) / divide

df.apply(subtract_and_divide, sub=5, divide=2)

               A     B     C     D
2000-01-01  32.0   9.5  29.5  36.0
2000-01-02   8.0  21.0  37.5  36.5
2000-01-03  17.0  14.5  10.5  -2.5
2000-01-04   8.0   1.0  23.5  35.0
2000-01-05  19.5  26.5  24.0  14.0
2000-01-06  30.0   2.0  47.0  41.5
2000-01-07  -2.0   2.0   3.0  35.5
2000-01-08  -0.5   3.5  35.0  39.0

In [ ]:
# Using apply with Series - apply function to each element in the Series
df['A'].apply(lambda x: x + 5)

2000-01-01    74
2000-01-02    26
2000-01-03    44
2000-01-04    26
2000-01-05    49
2000-01-06    70
2000-01-07     6
2000-01-08     9
Freq: D, Name: A, dtype: int64

###2. Applying elementwise functions
Since not all functions can be vectorized (accept NumPy arrays and return another array or value), the methods `applymap()` on **DataFrame** and analogously `map()` on **Series** accept any Python function *taking a single value and returning a single value.* For example:

In [ ]:
df2 = pd.DataFrame(
    [["Apple", 1, 100],
     ["Banana", 2, 50],
     ["Orange", 5, np.nan],
     ["Mango", 3, 250]],
    index=["a", "b", "c", "d"],
    columns=["Fruit", "Amount", "Price"]
)
df2

    Fruit  Amount  Price
a   Apple       1  100.0
b  Banana       2   50.0
c  Orange       5    NaN
d   Mango       3  250.0

In [ ]:
df2["Fruit"].map(len)

a    5
b    6
c    6
d    5
Name: Fruit, dtype: int64

In [ ]:
def get_len(e):
    return len(str(e))

df2.applymap(get_len)

<ipython-input-11-d2018368079a>:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df2.applymap(get_len)

   Fruit  Amount  Price
a      5       1      5
b      6       1      4
c      6       1      3
d      5       1      5

**EX: Student Alcohol Consumption**

In [5]:
csv_url = 'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv'
df = pd.read_csv(csv_url)
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

**For the purpose of this exercise slice the dataframe from 'school' until the 'guardian' column**

In [6]:
df = df.loc[:, 'school':'guardian']
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother
4,GP,F,16,U,GT3,T,3,3,other,other,home,father

**Create a lambda function that will capitalize strings.**

**[Hint]** using `.capitalize()` method

**Capitalize both `Mjob` and `Fjob`**

In [14]:
# YOUR CODE HERE
df.loc['Mjob':'Fjob'].map(lambda x:x.capitalize())
# df['Mjob'] = df['Mjob'].map(lambda x: x.capitalize())
# df['Fjob'] = df['Fjob'].map(lambda x: x.capitalize())
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
0,GP,F,18,U,GT3,A,4,4,At_home,Teacher,course,mother
1,GP,F,17,U,GT3,T,1,1,At_home,Other,course,father
2,GP,F,15,U,LE3,T,1,1,At_home,Other,other,mother
3,GP,F,15,U,GT3,T,4,2,Health,Services,home,mother
4,GP,F,16,U,GT3,T,3,3,Other,Other,home,father
...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,Services,Services,course,other
391,MS,M,17,U,LE3,T,3,1,Services,Services,course,mother
392,MS,M,21,R,GT3,T,1,1,Other,Other,course,other
393,MS,M,18,R,LE3,T,3,2,Services,Other,course,mother
394,MS,M,19,U,LE3,T,1,1,Other,At_home,course,father

**Create a function called `majority` that returns a boolean value to a new column called** `legal_drinker`

**(Consider majority as older than 17 years old)**

In [ ]:
# YOUR CODE HERE

In [15]:
df['legal_drinker'] = df['age'].apply(lambda x : x >= 17)
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,legal_drinker
0,GP,F,18,U,GT3,A,4,4,At_home,Teacher,course,mother,True
1,GP,F,17,U,GT3,T,1,1,At_home,Other,course,father,True
2,GP,F,15,U,LE3,T,1,1,At_home,Other,other,mother,False
3,GP,F,15,U,GT3,T,4,2,Health,Services,home,mother,False
4,GP,F,16,U,GT3,T,3,3,Other,Other,home,father,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,Services,Services,course,other,True
391,MS,M,17,U,LE3,T,3,1,Services,Services,course,mother,True
392,MS,M,21,R,GT3,T,1,1,Other,Other,course,other,True
393,MS,M,18,R,LE3,T,3,2,Services,Other,course,mother,True
394,MS,M,19,U,LE3,T,1,1,Other,At_home,course,father,True

###3. Tablewise function application
DataFrames and Series can be passed into functions.

In [ ]:
df_p = pd.DataFrame({"state_and_code": ["Illinois, IL", "California, CA", "Florida, FL"]})
df_p

   state_and_code
0    Illinois, IL
1  California, CA
2     Florida, FL

In [ ]:
def extract_state_name(df):
    """
    Illinois, IL -> Illinois for state_name column
    """
    df["state_name"] = df["state_and_code"].str.split(",").str.get(0)
    df["state_code"] = df["state_and_code"].str.split(",").str.get(1)
    return df

In [ ]:
df_p_state_name = extract_state_name(df_p)
df_p_state_name

   state_and_code  state_name state_code
0    Illinois, IL    Illinois         IL
1  California, CA  California         CA
2     Florida, FL     Florida         FL

## Grouping and aggregation

In [53]:
df = pd.read_csv('data/vgsales.csv')

This dataset contains a list of video games with sales greater than 100,000 copies. It was generated by a scrape of vgchartz.com.

**Fields include:**

- Rank - Ranking of overall sales
- Name - The game's name
- Platform - Platform of the games release (i.e. PC,PS4, etc.)
- Year - Year of the game's release
- Genre - Genre of the game
- Publisher - Publisher of the game
- NA_Sales - Sales in North America (in millions)
- EU_Sales - Sales in Europe (in millions)
- JP_Sales - Sales in Japan (in millions)
- Other_Sales - Sales in the rest of the world (in millions)
- Global_Sales - Total worldwide sales.

In [17]:
df.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

###value_counts

In [18]:
df['Platform'].value_counts()

Platform
DS      2163
PS2     2161
PS3     1329
Wii     1325
X360    1265
PSP     1213
PS      1196
PC       960
XB       824
GBA      822
GC       556
3DS      509
PSV      413
PS4      336
N64      319
SNES     239
XOne     213
SAT      173
WiiU     143
2600     133
NES       98
GB        98
DC        52
GEN       27
NG        12
SCD        6
WS         6
3DO        3
TG16       2
GG         1
PCFX       1
Name: count, dtype: int64

In [19]:
df.value_counts('Platform')

Platform
DS      2163
PS2     2161
PS3     1329
Wii     1325
X360    1265
PSP     1213
PS      1196
PC       960
XB       824
GBA      822
GC       556
3DS      509
PSV      413
PS4      336
N64      319
SNES     239
XOne     213
SAT      173
WiiU     143
2600     133
GB        98
NES       98
DC        52
GEN       27
NG        12
WS         6
SCD        6
3DO        3
TG16       2
PCFX       1
GG         1
Name: count, dtype: int64

In [20]:
df['Genre'].value_counts(normalize=True)
# normalize - if True then the object returned will contain
# the relative frequencies of the unique values.

Genre
Action          0.199783
Sports          0.141342
Misc            0.104772
Role-Playing    0.089649
Shooter         0.078925
Adventure       0.077479
Racing          0.075250
Platform        0.053380
Simulation      0.052235
Fighting        0.051090
Strategy        0.041029
Puzzle          0.035064
Name: proportion, dtype: float64

###Group by: split-apply-combine

By “group by” we are referring to a process involving one or more of the following steps:

- **Splitting** the data into groups based on some criteria.
- **Applying** a function to each group independently.
- **Combining** the results into a data structure.

Let's try to get status counts of each category.

In [21]:
df.groupby('Publisher')

In [22]:
df.groupby('Publisher')['Genre'].value_counts()[:20]

Publisher                     Genre
10TACLE Studios               Adventure        1
                              Puzzle           1
                              Strategy         1
1C Company                    Racing           1
                              Role-Playing     1
                              Strategy         1
20th Century Fox Video Games  Action           4
                              Shooter          1
2D Boy                        Puzzle           1
3DO                           Action          17
                              Sports           6
                              Shooter          5
                              Adventure        3
                              Fighting         1
                              Platform         1
                              Puzzle           1
                              Role-Playing     1
                              Strategy         1
49Games                       Sports           1
505 Games                     Simulation      41
Name: count, dtype: int64

In [ ]:
s = df.groupby(['Genre', 'Platform'])['Global_Sales'].sum()
s[:20]

Genre   Platform
Action  2600         29.34
        3DS          57.02
        DC            1.26
        DS          115.56
        GB            7.92
        GBA          55.76
        GC           37.84
        GEN           2.74
        N64          29.58
        NES          28.75
        PC           31.53
        PS          127.05
        PS2         272.76
        PS3         307.88
        PS4          87.06
        PSP          64.72
        PSV          20.01
        SAT           0.65
        SNES         10.08
        Wii         118.58
Name: Global_Sales, dtype: float64

In [ ]:
s[:20].unstack()

Platform,2600,3DS,DC,DS,GB,GBA,GC,GEN,N64,NES,PC,PS,PS2,PS3,PS4,PSP,PSV,SAT,SNES,Wii
Genre,,,,,,,,,,,,,,,,,,,,
Action,29.34,57.02,1.26,115.56,7.92,55.76,37.84,2.74,29.58,28.75,31.53,127.05,272.76,307.88,87.06,64.72,20.01,0.65,10.08,118.58

In [ ]:
df.groupby(['Genre', 'Platform'], as_index=False)['Global_Sales'].sum()

        Genre Platform  Global_Sales
0      Action     2600         29.34
1      Action      3DS         57.02
2      Action       DC          1.26
3      Action       DS        115.56
4      Action       GB          7.92
..        ...      ...           ...
288  Strategy      Wii          5.23
289  Strategy     WiiU          1.24
290  Strategy     X360         10.13
291  Strategy       XB          2.78
292  Strategy     XOne          0.38

[293 rows x 3 columns]

**EX: หาค่าเฉลี่ยของ `Global_Sales` ของ game แต่ละ `Genre` และทำการเรียงลำดับจากมากไปน้อย**

*Hint: เรียงลำดับด้วย `sort_values()` [ref](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html)*

In [23]:
# groupby ด้วย Genre
df.groupby('Genre')['Global_Sales'].mean().sort_values(ascending=False)

Genre
Platform        0.938341
Shooter         0.791885
Role-Playing    0.623233
Racing          0.586101
Sports          0.567319
Fighting        0.529375
Action          0.528100
Misc            0.465762
Simulation      0.452364
Puzzle          0.420876
Strategy        0.257151
Adventure       0.185879
Name: Global_Sales, dtype: float64

**EX: แสดงจำนวน game ในแต่ละ `Genre` สำหรับ game ใน `Platform` = `Wii` และ `X360`**

*Hint: use `.loc[]` to filter only Wii and X360*

In [27]:
# Code here
df.loc[df['Platform'].isin(['Wii','X360'])].groupby('Genre')['Name'].count()

Genre
Action          562
Adventure       131
Fighting        107
Misc            406
Platform         82
Puzzle           62
Racing          199
Role-Playing    111
Shooter         269
Simulation      127
Sports          481
Strategy         53
Name: Name, dtype: int64

###Aggregation

Once the GroupBy object has been created, several methods are available to perform a computation on the grouped data.

We can use the `agg()` method.

In [38]:
df.groupby('Genre')['Global_Sales'].agg({
    'Global_Sales_mean': 'mean',
    'Global_Sales_max': 'max',
    'Global_Sales_min': 'min',
    'Global_Sales_count': 'count'
})

SpecificationError: nested renamer is not supported

### Applying a function to each group independently

เรามาลองหาว่ามี game จำนวนเท่าไหร่ที่ได้ยอดขาย `JP_Sales` มากกว่า `NA_Sales` ในแต่ละ `Genre`

In [ ]:
def my_func(game):
  return len(game[game['JP_Sales'] > game['NA_Sales']])

df.groupby('Genre').apply(my_func)

Genre
Action          684
Adventure       675
Fighting        301
Misc            450
Platform         94
Puzzle          104
Racing           78
Role-Playing    772
Shooter         107
Simulation      201
Sports          427
Strategy        232
dtype: int64

**EX: ลองหาว่าสำหรับ game ที่ได้ยอดขาย `JP_Sales` มากกว่า `NA_Sales` ในแต่ละ `Genre` นั้นมีค่าเฉลี่ยของผลต่างยอดขาย `JP_Sales` - `NA_Sales` เท่าไหร่**

In [55]:
# Your code here
def my_func(game):
  mean_jp_sale = game['JP_Sales'].mean()
  mean_na_sale = game['NA_Sales'].mean()
  return mean_jp_sale - mean_na_sale
df[df['JP_Sales'] > df['NA_Sales']].groupby('Genre').apply(my_func)

/tmp/ipython-input-1419549329.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df[df['JP_Sales'] > df['NA_Sales']].groupby('Genre').apply(my_func)

Genre
Action          0.112646
Adventure       0.057807
Fighting        0.158073
Misc            0.159222
Platform        0.272553
Puzzle          0.271635
Racing          0.178718
Role-Playing    0.263355
Shooter         0.136075
Simulation      0.200995
Sports          0.220258
Strategy        0.176638
dtype: float64

## Joining DataFrames

With pandas, you can `merge`, `join`, and `concatenate` your datasets, allowing you to unify and better understand your data as you analyze it.

- `merge()` for combining data on common columns or indices
- `join()` for combining data on a key column or an index
- `concat()` for combining DataFrames across rows or columns

[Credit](https://realpython.com/pandas-merge-join-and-concat/)

### How to Use merge()

When you use `merge()`, you’ll provide two required arguments:

- The `left` DataFrame
- The `right` DataFrame

After that, you can provide a number of optional arguments to define how your datasets are merged:

- `how` defines what kind of merge to make. It defaults to 'inner', but other possible options include 'outer', 'left', and 'right'.

- `on` tells `merge()` which columns or indices, also called key columns or key indices, you want to join on. This is optional. If it isn’t specified, and `left_index` and `right_index` (covered below) are False, then columns from the two DataFrames that share names will be used as join keys. If you use `on`, then the column or index that you specify must be present in both objects.

- `left_on` and `right_on` specify a column or index that’s present only in the left or right object that you’re merging. Both default to None.

- `left_index` and `right_index` both default to False, but if you want to use the index of the left or right object to be merged, then you can set the relevant argument to True.

- `suffixes` is a tuple of strings to append to identical column names that aren’t merge keys. This allows you to keep track of the origins of columns with the same name.

![joins](https://files.realpython.com/media/join_diagram.93e6ef63afbe.png)

**Merge methods:**

- **left** => `LEFT OUTER JOIN` - Use keys from left frame only
- **right** => `RIGHT OUTER JOIN` - Use keys from right frame only
- **outer** => `FULL OUTER JOIN` - Use union of keys from both frames
- **inner** => `INNER JOIN` - Use intersection of keys from both frames

In [57]:
left = pd.DataFrame(
    {
        "key": ["K0", "K1", "K2", "K3"],
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
    }
)


right = pd.DataFrame(
    {
        "key": ["K0", "K1", "K2", "K3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    }
)

In [58]:
result = pd.merge(left, right, on="key")
result

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

We can also join with mutiple keys.

In this example, we join `left` and `right` with keys: `key1` and `key2`

In [59]:
left = pd.DataFrame(
   {
      "key1": ["K0", "K0", "K1", "K2"],
      "key2": ["K0", "K1", "K0", "K1"],
      "A": ["A0", "A1", "A2", "A3"],
      "B": ["B0", "B1", "B2", "B3"],
   }
)


right = pd.DataFrame(
   {
      "key1": ["K0", "K1", "K1", "K2"],
      "key2": ["K0", "K0", "K0", "K0"],
      "C": ["C0", "C1", "C2", "C3"],
      "D": ["D0", "D1", "D2", "D3"],
   }
)

In [60]:
result = pd.merge(left, right, how="left", on=["key1", "key2"])

result

  key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

#### Inner Join

In [ ]:
result = pd.merge(left, right, how="inner", on=["key1", "key2"])

result

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

#### Outer Join

In [61]:
result = pd.merge(left, right, how="outer", on=["key1", "key2"])

result

  key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K0  NaN  NaN   C3   D3
5   K2   K1   A3   B3  NaN  NaN

**Excercise**

Do `left` join between `products` and `categories`

In [62]:
products = pd.DataFrame({
    "ID": [1, 2, 3, 4, 5],
    "NAME": ["iPhone 15", "Galaxy Fold 6", "TV", "Pillow", "Generic Blanket"],
    "PRICE": [50000, 60000, 15000, 1200, 500],
    "CAT_ID": [1, 1, 2, 3, 3]
})
products

   ID             NAME  PRICE  CAT_ID
0   1        iPhone 15  50000       1
1   2    Galaxy Fold 6  60000       1
2   3               TV  15000       2
3   4           Pillow   1200       3
4   5  Generic Blanket    500       3

In [65]:
categories = pd.DataFrame({
    "ID": [1, 2, 3, 4, 5],
    "NAME": ["Mobile", "Electronics", "Household", "Kitchen", "Toys"]
})
categories

   ID         NAME
0   1       Mobile
1   2  Electronics
2   3    Household
3   4      Kitchen
4   5         Toys

In [66]:
# YOUR CODE HERE
result = pd.merge(products,categories,how='left', left_on="CAT_ID", right_on="ID")
result

   ID_x           NAME_x  PRICE  CAT_ID  ID_y       NAME_y
0     1        iPhone 15  50000       1     1       Mobile
1     2    Galaxy Fold 6  60000       1     1       Mobile
2     3               TV  15000       2     2  Electronics
3     4           Pillow   1200       3     3    Household
4     5  Generic Blanket    500       3     3    Household

Now, let's do `right` join between `products` and `categories`

In [70]:
# YOUR CODE HERE
rs = pd.merge(products,categories, how='right', left_on="CAT_ID",right_on="ID")

   ID_x           NAME_x    PRICE  CAT_ID  ID_y       NAME_y
0   1.0        iPhone 15  50000.0     1.0     1       Mobile
1   2.0    Galaxy Fold 6  60000.0     1.0     1       Mobile
2   3.0               TV  15000.0     2.0     2  Electronics
3   4.0           Pillow   1200.0     3.0     3    Household
4   5.0  Generic Blanket    500.0     3.0     3    Household
5   NaN              NaN      NaN     NaN     4      Kitchen
6   NaN              NaN      NaN     NaN     5         Toys

From the joined dataframe, can you find number of product in each product category.

In [74]:
# YOUR CODE HERE
rs.groupby('NAME_y').agg({
    'ID_x': 'count'
})

result.groupby('NAME_y')['ID_x'].count()

NAME_y
Electronics    1
Household      2
Mobile         2
Name: ID_x, dtype: int64

### .join()
`.join()` uses `merge()` under the hood, but provides a much more simplified interface to `merge()` and by default joins on indexes.

In [ ]:
left = pd.DataFrame(
    {"A": ["A0", "A1", "A2"], "B": ["B0", "B1", "B2"]}, index=["K0", "K1", "K2"]
)


right = pd.DataFrame(
    {"C": ["C0", "C2", "C3"], "D": ["D0", "D2", "D3"]}, index=["K0", "K2", "K3"]
)

In [79]:
left

  key1 key2   A   B
0   K0   K0  A0  B0
1   K0   K1  A1  B1
2   K1   K0  A2  B2
3   K2   K1  A3  B3

In [80]:
right

  key1 key2   C   D
0   K0   K0  C0  D0
1   K1   K0  C1  D1
2   K1   K0  C2  D2
3   K2   K0  C3  D3

In [ ]:
left.join(right, how="inner")

     A   B   C   D
K0  A0  B0  C0  D0
K2  A2  B2  C2  D2

### concat()

First, you will see a basic concatenation along axis 0.

In [82]:
reindexed = pd.concat(
    [left, right], ignore_index=True,axis=1
)
reindexed

    0   1   2   3   4   5   6   7
0  K0  K0  A0  B0  K0  K0  C0  D0
1  K0  K1  A1  B1  K1  K0  C1  D1
2  K1  K0  A2  B2  K1  K0  C2  D2
3  K2  K1  A3  B3  K2  K0  C3  D3

In [83]:
results = pd.concat(
    [left, right], axis=1
)
results

  key1 key2   A   B key1 key2   C   D
0   K0   K0  A0  B0   K0   K0  C0  D0
1   K0   K1  A1  B1   K1   K0  C1  D1
2   K1   K0  A2  B2   K1   K0  C2  D2
3   K2   K1  A3  B3   K2   K0  C3  D3

In [84]:
results = pd.concat(
    [left, right], axis=1, join="inner"
)
results

  key1 key2   A   B key1 key2   C   D
0   K0   K0  A0  B0   K0   K0  C0  D0
1   K0   K1  A1  B1   K1   K0  C1  D1
2   K1   K0  A2  B2   K1   K0  C2  D2
3   K2   K1  A3  B3   K2   K0  C3  D3